# Generated by Django 3.2.7 on 2021-09-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_auto_20210922_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('low', 'Low')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('contacted', 'Contacted'), ('new', 'New'), ('lost', 'Lost'), ('inprogress', 'In progress'), ('won', 'Won')], default='new', max_length=25),
        ),
    ]
