# Generated by Django 3.2.7 on 2021-09-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20210923_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('medium', 'Medium')], default='medium', max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('won', 'Won'), ('contacted', 'Contacted'), ('inprogress', 'In progress'), ('lost', 'Lost')], default='new', max_length=25),
        ),
    ]
